=== Cristfe/XML-Y-XSD/libros.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="Libros">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="libro" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="libro">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="título" type="xs:string" maxOccurs="unbounded"/>
        <xs:element name="autor" type="xs:string" maxOccurs="unbounded"/>
        <xs:element name="año" type="xs:string"/>
        <xs:element name="precio" type="xs:string"/>
      </xs:sequence>
      <xs:attribute name="género" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Cristfe/XML-Y-XSD/Libros.xml
<?xml version="1.0" encoding="UTF-8"?>
<Libros xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="libros.xsd">
   <libro género="NOVELA HISTÓRICA">
     <título>SIDI</título>
     <autor>Arturo Pérez Reverte</autor>
     <año>2019</año>
     <precio>19.85</precio>
    </libro>
   <libro género="INFORMÁTICA">
     <título>Iniciación a XQuery</título>
     <autor>James McGovern</autor>
     <autor>Per Bothner</autor>
     <autor>Kurt Cagle</autor>
     <autor>James Linn</autor>
     <autor>Vaidyanathan Nagarajan</autor>
     <año>2003</año>
     <precio>49.99</precio>
   </libro>
   <libro género="INFORMÁTICA">
      <título>Learning XML</título>
     <autor>Erik.T.Ray</autor>
     <año>2003</año>
     <precio>39.95</precio>
    </libro>
</Libros>
